name: frontend
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.12.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.2
  http: ^1.6.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/perfumery/catalog.json
    - assets/perfumery/catalog-suggestions/feminine/afnan/
    - assets/perfumery/catalog-suggestions/feminine/ahli/
    - assets/perfumery/catalog-suggestions/feminine/al-haramain/
    - assets/perfumery/catalog-suggestions/feminine/alexandre-j/
    - assets/perfumery/catalog-suggestions/feminine/amouage/
    - assets/perfumery/catalog-suggestions/feminine/animale/
    - assets/perfumery/catalog-suggestions/feminine/antonio-banderas/
    - assets/perfumery/catalog-suggestions/feminine/ariana-grande/
    - assets/perfumery/catalog-suggestions/feminine/armaf/
    - assets/perfumery/catalog-suggestions/feminine/asdaaf/
    - assets/perfumery/catalog-suggestions/feminine/bad-body-works/
    - assets/perfumery/catalog-suggestions/feminine/bath-body-works/
    - assets/perfumery/catalog-suggestions/feminine/bharara/
    - assets/perfumery/catalog-suggestions/feminine/bond-no-9/
    - assets/perfumery/catalog-suggestions/feminine/britney-spears/
    - assets/perfumery/catalog-suggestions/feminine/burberry/
    - assets/perfumery/catalog-suggestions/feminine/bvlgari/
    - assets/perfumery/catalog-suggestions/feminine/cacharel/
    - assets/perfumery/catalog-suggestions/feminine/calvin-klein/
    - assets/perfumery/catalog-suggestions/feminine/carolina-herrera/
    - assets/perfumery/catalog-suggestions/feminine/cartier/
    - assets/perfumery/catalog-suggestions/feminine/chanel/
    - assets/perfumery/catalog-suggestions/feminine/clinique/
    - assets/perfumery/catalog-suggestions/feminine/coach/
    - assets/perfumery/catalog-suggestions/feminine/creed/
    - assets/perfumery/catalog-suggestions/feminine/diesel/
    - assets/perfumery/catalog-suggestions/feminine/dior/
    - assets/perfumery/catalog-suggestions/feminine/dolce-gabbana/
    - assets/perfumery/catalog-suggestions/feminine/donna-karan/
    - assets/perfumery/catalog-suggestions/feminine/elizabeth-arden/
    - assets/perfumery/catalog-suggestions/feminine/elizabeth-taylor/
    - assets/perfumery/catalog-suggestions/feminine/escada/
    - assets/perfumery/catalog-suggestions/feminine/franck-olivier/
    - assets/perfumery/catalog-suggestions/feminine/fred-hayman/
    - assets/perfumery/catalog-suggestions/feminine/giorgio-armani/
    - assets/perfumery/catalog-suggestions/feminine/givenchy/
    - assets/perfumery/catalog-suggestions/feminine/gucci/
    - assets/perfumery/catalog-suggestions/feminine/guess/
    - assets/perfumery/catalog-suggestions/feminine/halloween/
    - assets/perfumery/catalog-suggestions/feminine/hugo-boss/
    - assets/perfumery/catalog-suggestions/feminine/ilmin/
    - assets/perfumery/catalog-suggestions/feminine/issey-miyake/
    - assets/perfumery/catalog-suggestions/feminine/jean-paul-gaultier/
    - assets/perfumery/catalog-suggestions/feminine/juicy-couture/
    - assets/perfumery/catalog-suggestions/feminine/justin-bieber/
    - assets/perfumery/catalog-suggestions/feminine/katy-perry/
    - assets/perfumery/catalog-suggestions/feminine/kenzo/
    - assets/perfumery/catalog-suggestions/feminine/kim-kardashian/
    - assets/perfumery/catalog-suggestions/feminine/lacoste/
    - assets/perfumery/catalog-suggestions/feminine/lancome/
    - assets/perfumery/catalog-suggestions/feminine/lattafa/
    - assets/perfumery/catalog-suggestions/feminine/laverne/
    - assets/perfumery/catalog-suggestions/feminine/lolita-lempicka/
    - assets/perfumery/catalog-suggestions/feminine/louis-vuitton/
    - assets/perfumery/catalog-suggestions/feminine/marly/
    - assets/perfumery/catalog-suggestions/feminine/montale/
    - assets/perfumery/catalog-suggestions/feminine/montblanc/
    - assets/perfumery/catalog-suggestions/feminine/moschino/
    - assets/perfumery/catalog-suggestions/feminine/mugler/
    - assets/perfumery/catalog-suggestions/feminine/narciso-rodriguez/
    - assets/perfumery/catalog-suggestions/feminine/natura/
    - assets/perfumery/catalog-suggestions/feminine/nina-ricci/
    - assets/perfumery/catalog-suggestions/feminine/one-direction/
    - assets/perfumery/catalog-suggestions/feminine/orientica/
    - assets/perfumery/catalog-suggestions/feminine/paris-hilton/
    - assets/perfumery/catalog-suggestions/feminine/perry-ellis/
    - assets/perfumery/catalog-suggestions/feminine/prada/
    - assets/perfumery/catalog-suggestions/feminine/rabanne/
    - assets/perfumery/catalog-suggestions/feminine/ralph-lauren/
    - assets/perfumery/catalog-suggestions/feminine/roberto-cavalli/
    - assets/perfumery/catalog-suggestions/feminine/rolex/
    - assets/perfumery/catalog-suggestions/feminine/royalty-by-maluma/
    - assets/perfumery/catalog-suggestions/feminine/selena-gomez/
    - assets/perfumery/catalog-suggestions/feminine/shakira/
    - assets/perfumery/catalog-suggestions/feminine/sofia-vergara/
    - assets/perfumery/catalog-suggestions/feminine/tom-ford/
    - assets/perfumery/catalog-suggestions/feminine/tommy-hilfiger/
    - assets/perfumery/catalog-suggestions/feminine/tous/
    - assets/perfumery/catalog-suggestions/feminine/valentino/
    - assets/perfumery/catalog-suggestions/feminine/versace/
    - assets/perfumery/catalog-suggestions/feminine/victoria-s-secret/
    - assets/perfumery/catalog-suggestions/feminine/victorinox-swiss-army/
    - assets/perfumery/catalog-suggestions/feminine/viktor-rolf/
    - assets/perfumery/catalog-suggestions/feminine/xerjoff/
    - assets/perfumery/catalog-suggestions/feminine/yanbal/
    - assets/perfumery/catalog-suggestions/feminine/yves-saint-laurent/
    - assets/perfumery/catalog-suggestions/masculine/abercrombie-fitch/
    - assets/perfumery/catalog-suggestions/masculine/afnan/
    - assets/perfumery/catalog-suggestions/masculine/al-haramain/
    - assets/perfumery/catalog-suggestions/masculine/amouage/
    - assets/perfumery/catalog-suggestions/masculine/animale/
    - assets/perfumery/catalog-suggestions/masculine/antonio-banderas/
    - assets/perfumery/catalog-suggestions/masculine/armaf/
    - assets/perfumery/catalog-suggestions/masculine/asdaaf/
    - assets/perfumery/catalog-suggestions/masculine/azzaro/
    - assets/perfumery/catalog-suggestions/masculine/bharara/
    - assets/perfumery/catalog-suggestions/masculine/bond-no-9/
    - assets/perfumery/catalog-suggestions/masculine/burberry/
    - assets/perfumery/catalog-suggestions/masculine/bvlgari/
    - assets/perfumery/catalog-suggestions/masculine/calvin-klein/
    - assets/perfumery/catalog-suggestions/masculine/carolina-herrera/
    - assets/perfumery/catalog-suggestions/masculine/cartier/
    - assets/perfumery/catalog-suggestions/masculine/chanel/
    - assets/perfumery/catalog-suggestions/masculine/clinique/
    - assets/perfumery/catalog-suggestions/masculine/creed/
    - assets/perfumery/catalog-suggestions/masculine/cristiano-ronaldo/
    - assets/perfumery/catalog-suggestions/masculine/david-beckham/
    - assets/perfumery/catalog-suggestions/masculine/diesel/
    - assets/perfumery/catalog-suggestions/masculine/dior/
    - assets/perfumery/catalog-suggestions/masculine/dolce-gabbana/
    - assets/perfumery/catalog-suggestions/masculine/dumont/
    - assets/perfumery/catalog-suggestions/masculine/el-ganso/
    - assets/perfumery/catalog-suggestions/masculine/enrique-iglesias/
    - assets/perfumery/catalog-suggestions/masculine/esika/
    - assets/perfumery/catalog-suggestions/masculine/faconnable/
    - assets/perfumery/catalog-suggestions/masculine/ferrari/
    - assets/perfumery/catalog-suggestions/masculine/gilles-cantuel/
    - assets/perfumery/catalog-suggestions/masculine/giorgio-armani/
    - assets/perfumery/catalog-suggestions/masculine/givenchi/
    - assets/perfumery/catalog-suggestions/masculine/givenchy/
    - assets/perfumery/catalog-suggestions/masculine/gucci/
    - assets/perfumery/catalog-suggestions/masculine/halloween/
    - assets/perfumery/catalog-suggestions/masculine/hugo-boss/
    - assets/perfumery/catalog-suggestions/masculine/issey-miyake/
    - assets/perfumery/catalog-suggestions/masculine/jean-pascal/
    - assets/perfumery/catalog-suggestions/masculine/jean-paul-gaultier/
    - assets/perfumery/catalog-suggestions/masculine/joop/
    - assets/perfumery/catalog-suggestions/masculine/karl-lagerfeld/
    - assets/perfumery/catalog-suggestions/masculine/lacoste/
    - assets/perfumery/catalog-suggestions/masculine/laroche/
    - assets/perfumery/catalog-suggestions/masculine/lattafa/
    - assets/perfumery/catalog-suggestions/masculine/liz-claiborne/
    - assets/perfumery/catalog-suggestions/masculine/loewe/
    - assets/perfumery/catalog-suggestions/masculine/louis-vuitton/
    - assets/perfumery/catalog-suggestions/masculine/marly/
    - assets/perfumery/catalog-suggestions/masculine/montblanc/
    - assets/perfumery/catalog-suggestions/masculine/moschino/
    - assets/perfumery/catalog-suggestions/masculine/mugler/
    - assets/perfumery/catalog-suggestions/masculine/nautica/
    - assets/perfumery/catalog-suggestions/masculine/orientica/
    - assets/perfumery/catalog-suggestions/masculine/oscar-de-la-renta/
    - assets/perfumery/catalog-suggestions/masculine/paris-hilton/
    - assets/perfumery/catalog-suggestions/masculine/penhaligon-s/
    - assets/perfumery/catalog-suggestions/masculine/perry-ellis/
    - assets/perfumery/catalog-suggestions/masculine/philipp-plein/
    - assets/perfumery/catalog-suggestions/masculine/pino-silvestre/
    - assets/perfumery/catalog-suggestions/masculine/prada/
    - assets/perfumery/catalog-suggestions/masculine/rabanne/
    - assets/perfumery/catalog-suggestions/masculine/ralph-lauren/
    - assets/perfumery/catalog-suggestions/masculine/rasasi/
    - assets/perfumery/catalog-suggestions/masculine/revlon/
    - assets/perfumery/catalog-suggestions/masculine/reyane-tradition/
    - assets/perfumery/catalog-suggestions/masculine/rolex/
    - assets/perfumery/catalog-suggestions/masculine/royalty-by-maluma/
    - assets/perfumery/catalog-suggestions/masculine/ted-lapidus/
    - assets/perfumery/catalog-suggestions/masculine/tom-ford/
    - assets/perfumery/catalog-suggestions/masculine/tommy-hilfiger/
    - assets/perfumery/catalog-suggestions/masculine/valentino/
    - assets/perfumery/catalog-suggestions/masculine/versace/
    - assets/perfumery/catalog-suggestions/masculine/victorinox-swiss-army/
    - assets/perfumery/catalog-suggestions/masculine/viktor-rolf/
    - assets/perfumery/catalog-suggestions/masculine/yanbal/
    - assets/perfumery/catalog-suggestions/masculine/yves-saint-lauren/
    - assets/perfumery/catalog-suggestions/masculine/yves-saint-laurent/
    - assets/perfumery/catalog-suggestions/masculine/zlatan-ibrahimovic/
    - assets/perfumery/catalog-suggestions/unisex/afnan/
    - assets/perfumery/catalog-suggestions/unisex/ahli/
    - assets/perfumery/catalog-suggestions/unisex/al-haramain/
    - assets/perfumery/catalog-suggestions/unisex/alexandre-j/
    - assets/perfumery/catalog-suggestions/unisex/armaf/
    - assets/perfumery/catalog-suggestions/unisex/atelier-versace/
    - assets/perfumery/catalog-suggestions/unisex/bharara/
    - assets/perfumery/catalog-suggestions/unisex/bond-no-9/
    - assets/perfumery/catalog-suggestions/unisex/bons-no-9/
    - assets/perfumery/catalog-suggestions/unisex/by-kilian/
    - assets/perfumery/catalog-suggestions/unisex/creed/
    - assets/perfumery/catalog-suggestions/unisex/emirato/
    - assets/perfumery/catalog-suggestions/unisex/emirato-1/
    - assets/perfumery/catalog-suggestions/unisex/emirato-2/
    - assets/perfumery/catalog-suggestions/unisex/emirato-3/
    - assets/perfumery/catalog-suggestions/unisex/emirato-5/
    - assets/perfumery/catalog-suggestions/unisex/emirato-6/
    - assets/perfumery/catalog-suggestions/unisex/emirato-7/
    - assets/perfumery/catalog-suggestions/unisex/emper/
    - assets/perfumery/catalog-suggestions/unisex/ex-nihilo/
    - assets/perfumery/catalog-suggestions/unisex/french-avenue/
    - assets/perfumery/catalog-suggestions/unisex/giardini-di-toscana/
    - assets/perfumery/catalog-suggestions/unisex/guerlain/
    - assets/perfumery/catalog-suggestions/unisex/ilmin/
    - assets/perfumery/catalog-suggestions/unisex/initio/
    - assets/perfumery/catalog-suggestions/unisex/jomilano-paris/
    - assets/perfumery/catalog-suggestions/unisex/kayali/
    - assets/perfumery/catalog-suggestions/unisex/lattafa/
    - assets/perfumery/catalog-suggestions/unisex/le-labo/
    - assets/perfumery/catalog-suggestions/unisex/louis-vuitton/
    - assets/perfumery/catalog-suggestions/unisex/maison-crivelli/
    - assets/perfumery/catalog-suggestions/unisex/maison-francis-kurkdjian/
    - assets/perfumery/catalog-suggestions/unisex/mancera/
    - assets/perfumery/catalog-suggestions/unisex/marly/
    - assets/perfumery/catalog-suggestions/unisex/montale/
    - assets/perfumery/catalog-suggestions/unisex/moschino/
    - assets/perfumery/catalog-suggestions/unisex/orientica/
    - assets/perfumery/catalog-suggestions/unisex/roger-gallet/
    - assets/perfumery/catalog-suggestions/unisex/second-edition-olfactive/
    - assets/perfumery/catalog-suggestions/unisex/stephane-humbert-lucas-777/
    - assets/perfumery/catalog-suggestions/unisex/superz-budapest/
    - assets/perfumery/catalog-suggestions/unisex/tiziana-terenzi/
    - assets/perfumery/catalog-suggestions/unisex/tom-ford/
    - assets/perfumery/catalog-suggestions/unisex/vega/
    - assets/perfumery/catalog-suggestions/unisex/versace/
    - assets/perfumery/catalog-suggestions/unisex/xerjoff/
    - assets/perfumery/catalog-suggestions/unisex/zakat/
    - assets/productos/
    - assets/productos/good_girl/
    - assets/img/
    - assets/Carrusel/


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
